<?php
/**
 * Макет главной страницы (по умолчанию).
 * 
 * @package Theme
 * @subpackage Sample
 * @since 1.0
 *
 * @var \Gm\View\LayoutView $this 
 * @var string $content
 */

$this->registerAsset('main');
?>
<!DOCTYPE HTML>
<html lang="<?= $this->getLang() ?>">
<head>
    <meta charset="<?= $this->getCharset() ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->head() ?>
</head>

<body>
<?php $this->beginBody() ?>
<header>
<?= $this->renderFrom('partials/header') ?>
</header>

<?= $content ?>

<?= $this->renderFrom('partials/footer') ?>
<?php $this->endBody() ?>
</body>

</html>