<?php
/**
 * Шаблон ошибки 423 (Locked).
 * 
 * @package Theme
 * @subpackage Sample
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка 423 (Страница заблокирована)</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <!-- theme CSS -->
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/styles.css') ?>" />
</head>

<body>
    <h2>Ошибка 423 (Страница заблокирована)</h2>
    <p>К сожалению, такой страницы не существует.</p>
    <p>Вероятно, у Вас нет доступа или Ваш IP-адрес добавлен в чёрный список.</p>
</body>
</html>