<?php
/**
 * Шаблон ошибки подключения к базе данных.
 * 
 * @package Theme
 * @subpackage Sample
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка подключения к базе данных</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <!-- theme CSS -->
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/styles.css') ?>" />
</head>

<body>
    <h2>IP адрес заблокирован</h2>
    <p><?= $exception->getDispatch() ?></p>
</body>
</html>