<?php
/**
 * Шаблон ошибки 503 (Service Temporary Unavailability).
 * 
 * @author Anton Tivonenko <anton.tivonenko@gmail.com>
 * @copyright Copyright (c) 2015 GearMagic Web-студия
 * @package Theme
 * @subpackage Sample
 * @since 1.0
 */
?>
<!DOCTYPE HTML>
<html lang="ru-RU">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ошибка 503 (Сайт временно недоступен)</title>
    <link type="image/png" href="<?= Gm::getAlias('@theme::/assets/ico/favicon.ico') ?>" rel="icon" sizes="16x16">
    <!-- theme CSS -->
    <link rel="stylesheet" href="<?= Gm::getAlias('@theme::/assets/css/styles.css') ?>" />
</head>

<body>
    <h2>Ошибка 503 (Сайт временно недоступен)</h2>
    <p>Приносим свои извинения. Сайт временно недоступен и находится на техническом обслуживании.</p>
</body>
</html>